
title: My Resume
url: 'https://github.com/khangnpq'
baseurl: '/CV' #change it according to your repository name



# Profile information
yourname: Khang Quy Nguyen-Phuoc  ## put your name
title: 'Business Intelligence Analyst'  ## your title
location: Ho Chi Minh city, Vietnam


## Social Profiles
facebook: http://www.facebook.com/khang.nguyen042  ## your facebook account url
# twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com/in/khangnpq  ## your linkedin account url
# dribbble: http://www.dribble.com  ## you dribbble account url
# foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
